#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K5.v3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="K5_DB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKomplektu_Detale(Komplektu_Detale instance);
    partial void UpdateKomplektu_Detale(Komplektu_Detale instance);
    partial void DeleteKomplektu_Detale(Komplektu_Detale instance);
    partial void InsertKomplektai(Komplektai instance);
    partial void UpdateKomplektai(Komplektai instance);
    partial void DeleteKomplektai(Komplektai instance);
    partial void InsertParduotosDetale(ParduotosDetale instance);
    partial void UpdateParduotosDetale(ParduotosDetale instance);
    partial void DeleteParduotosDetale(ParduotosDetale instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::K5.v3.Properties.Settings.Default.K5_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Komplektu_Detale> Komplektu_Detales
		{
			get
			{
				return this.GetTable<Komplektu_Detale>();
			}
		}
		
		public System.Data.Linq.Table<Komplektai> Komplektais
		{
			get
			{
				return this.GetTable<Komplektai>();
			}
		}
		
		public System.Data.Linq.Table<ParduotosDetale> ParduotosDetales
		{
			get
			{
				return this.GetTable<ParduotosDetale>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Komplektu_Detales")]
	public partial class Komplektu_Detale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DetKodas;
		
		private string _DetAnalog1;
		
		private string _DetAnalog2;
		
		private string _DetAnalog3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetKodasChanging(string value);
    partial void OnDetKodasChanged();
    partial void OnDetAnalog1Changing(string value);
    partial void OnDetAnalog1Changed();
    partial void OnDetAnalog2Changing(string value);
    partial void OnDetAnalog2Changed();
    partial void OnDetAnalog3Changing(string value);
    partial void OnDetAnalog3Changed();
    #endregion
		
		public Komplektu_Detale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetKodas", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DetKodas
		{
			get
			{
				return this._DetKodas;
			}
			set
			{
				if ((this._DetKodas != value))
				{
					this.OnDetKodasChanging(value);
					this.SendPropertyChanging();
					this._DetKodas = value;
					this.SendPropertyChanged("DetKodas");
					this.OnDetKodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetAnalog1", DbType="NVarChar(20)")]
		public string DetAnalog1
		{
			get
			{
				return this._DetAnalog1;
			}
			set
			{
				if ((this._DetAnalog1 != value))
				{
					this.OnDetAnalog1Changing(value);
					this.SendPropertyChanging();
					this._DetAnalog1 = value;
					this.SendPropertyChanged("DetAnalog1");
					this.OnDetAnalog1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetAnalog2", DbType="NVarChar(20)")]
		public string DetAnalog2
		{
			get
			{
				return this._DetAnalog2;
			}
			set
			{
				if ((this._DetAnalog2 != value))
				{
					this.OnDetAnalog2Changing(value);
					this.SendPropertyChanging();
					this._DetAnalog2 = value;
					this.SendPropertyChanged("DetAnalog2");
					this.OnDetAnalog2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetAnalog3", DbType="NVarChar(20)")]
		public string DetAnalog3
		{
			get
			{
				return this._DetAnalog3;
			}
			set
			{
				if ((this._DetAnalog3 != value))
				{
					this.OnDetAnalog3Changing(value);
					this.SendPropertyChanging();
					this._DetAnalog3 = value;
					this.SendPropertyChanged("DetAnalog3");
					this.OnDetAnalog3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Komplektai")]
	public partial class Komplektai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _KomplektoKodas;
		
		private string _Pavadinimas;
		
		private string _Det1Kodas;
		
		private System.Nullable<int> _Det1Kiekis;
		
		private string _Det2Kodas;
		
		private System.Nullable<int> _Det2Kiekis;
		
		private string _Det3Kodas;
		
		private System.Nullable<int> _Det3Kiekis;
		
		private string _Det4Kodas;
		
		private System.Nullable<int> _Det4Kiekis;
		
		private string _Det5Kodas;
		
		private System.Nullable<int> _Det5Kiekis;
		
		private string _Det6Kodas;
		
		private System.Nullable<int> _Det6Kiekis;
		
		private string _Det7Kodas;
		
		private System.Nullable<int> _Det7Kiekis;
		
		private string _Det8Kodas;
		
		private System.Nullable<int> _Det8Kiekis;
		
		private string _Det9Kodas;
		
		private System.Nullable<int> _Det9Kiekis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnKomplektoKodasChanging(string value);
    partial void OnKomplektoKodasChanged();
    partial void OnPavadinimasChanging(string value);
    partial void OnPavadinimasChanged();
    partial void OnDet1KodasChanging(string value);
    partial void OnDet1KodasChanged();
    partial void OnDet1KiekisChanging(System.Nullable<int> value);
    partial void OnDet1KiekisChanged();
    partial void OnDet2KodasChanging(string value);
    partial void OnDet2KodasChanged();
    partial void OnDet2KiekisChanging(System.Nullable<int> value);
    partial void OnDet2KiekisChanged();
    partial void OnDet3KodasChanging(string value);
    partial void OnDet3KodasChanged();
    partial void OnDet3KiekisChanging(System.Nullable<int> value);
    partial void OnDet3KiekisChanged();
    partial void OnDet4KodasChanging(string value);
    partial void OnDet4KodasChanged();
    partial void OnDet4KiekisChanging(System.Nullable<int> value);
    partial void OnDet4KiekisChanged();
    partial void OnDet5KodasChanging(string value);
    partial void OnDet5KodasChanged();
    partial void OnDet5KiekisChanging(System.Nullable<int> value);
    partial void OnDet5KiekisChanged();
    partial void OnDet6KodasChanging(string value);
    partial void OnDet6KodasChanged();
    partial void OnDet6KiekisChanging(System.Nullable<int> value);
    partial void OnDet6KiekisChanged();
    partial void OnDet7KodasChanging(string value);
    partial void OnDet7KodasChanged();
    partial void OnDet7KiekisChanging(System.Nullable<int> value);
    partial void OnDet7KiekisChanged();
    partial void OnDet8KodasChanging(string value);
    partial void OnDet8KodasChanged();
    partial void OnDet8KiekisChanging(System.Nullable<int> value);
    partial void OnDet8KiekisChanged();
    partial void OnDet9KodasChanging(string value);
    partial void OnDet9KodasChanged();
    partial void OnDet9KiekisChanging(System.Nullable<int> value);
    partial void OnDet9KiekisChanged();
    #endregion
		
		public Komplektai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KomplektoKodas", DbType="NVarChar(20)")]
		public string KomplektoKodas
		{
			get
			{
				return this._KomplektoKodas;
			}
			set
			{
				if ((this._KomplektoKodas != value))
				{
					this.OnKomplektoKodasChanging(value);
					this.SendPropertyChanging();
					this._KomplektoKodas = value;
					this.SendPropertyChanged("KomplektoKodas");
					this.OnKomplektoKodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pavadinimas", DbType="NVarChar(MAX)")]
		public string Pavadinimas
		{
			get
			{
				return this._Pavadinimas;
			}
			set
			{
				if ((this._Pavadinimas != value))
				{
					this.OnPavadinimasChanging(value);
					this.SendPropertyChanging();
					this._Pavadinimas = value;
					this.SendPropertyChanged("Pavadinimas");
					this.OnPavadinimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det1Kodas", DbType="NVarChar(20)")]
		public string Det1Kodas
		{
			get
			{
				return this._Det1Kodas;
			}
			set
			{
				if ((this._Det1Kodas != value))
				{
					this.OnDet1KodasChanging(value);
					this.SendPropertyChanging();
					this._Det1Kodas = value;
					this.SendPropertyChanged("Det1Kodas");
					this.OnDet1KodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det1Kiekis", DbType="Int")]
		public System.Nullable<int> Det1Kiekis
		{
			get
			{
				return this._Det1Kiekis;
			}
			set
			{
				if ((this._Det1Kiekis != value))
				{
					this.OnDet1KiekisChanging(value);
					this.SendPropertyChanging();
					this._Det1Kiekis = value;
					this.SendPropertyChanged("Det1Kiekis");
					this.OnDet1KiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det2Kodas", DbType="NVarChar(20)")]
		public string Det2Kodas
		{
			get
			{
				return this._Det2Kodas;
			}
			set
			{
				if ((this._Det2Kodas != value))
				{
					this.OnDet2KodasChanging(value);
					this.SendPropertyChanging();
					this._Det2Kodas = value;
					this.SendPropertyChanged("Det2Kodas");
					this.OnDet2KodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det2Kiekis", DbType="Int")]
		public System.Nullable<int> Det2Kiekis
		{
			get
			{
				return this._Det2Kiekis;
			}
			set
			{
				if ((this._Det2Kiekis != value))
				{
					this.OnDet2KiekisChanging(value);
					this.SendPropertyChanging();
					this._Det2Kiekis = value;
					this.SendPropertyChanged("Det2Kiekis");
					this.OnDet2KiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det3Kodas", DbType="NVarChar(20)")]
		public string Det3Kodas
		{
			get
			{
				return this._Det3Kodas;
			}
			set
			{
				if ((this._Det3Kodas != value))
				{
					this.OnDet3KodasChanging(value);
					this.SendPropertyChanging();
					this._Det3Kodas = value;
					this.SendPropertyChanged("Det3Kodas");
					this.OnDet3KodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det3Kiekis", DbType="Int")]
		public System.Nullable<int> Det3Kiekis
		{
			get
			{
				return this._Det3Kiekis;
			}
			set
			{
				if ((this._Det3Kiekis != value))
				{
					this.OnDet3KiekisChanging(value);
					this.SendPropertyChanging();
					this._Det3Kiekis = value;
					this.SendPropertyChanged("Det3Kiekis");
					this.OnDet3KiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det4Kodas", DbType="NVarChar(20)")]
		public string Det4Kodas
		{
			get
			{
				return this._Det4Kodas;
			}
			set
			{
				if ((this._Det4Kodas != value))
				{
					this.OnDet4KodasChanging(value);
					this.SendPropertyChanging();
					this._Det4Kodas = value;
					this.SendPropertyChanged("Det4Kodas");
					this.OnDet4KodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det4Kiekis", DbType="Int")]
		public System.Nullable<int> Det4Kiekis
		{
			get
			{
				return this._Det4Kiekis;
			}
			set
			{
				if ((this._Det4Kiekis != value))
				{
					this.OnDet4KiekisChanging(value);
					this.SendPropertyChanging();
					this._Det4Kiekis = value;
					this.SendPropertyChanged("Det4Kiekis");
					this.OnDet4KiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det5Kodas", DbType="NChar(20)")]
		public string Det5Kodas
		{
			get
			{
				return this._Det5Kodas;
			}
			set
			{
				if ((this._Det5Kodas != value))
				{
					this.OnDet5KodasChanging(value);
					this.SendPropertyChanging();
					this._Det5Kodas = value;
					this.SendPropertyChanged("Det5Kodas");
					this.OnDet5KodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det5Kiekis", DbType="Int")]
		public System.Nullable<int> Det5Kiekis
		{
			get
			{
				return this._Det5Kiekis;
			}
			set
			{
				if ((this._Det5Kiekis != value))
				{
					this.OnDet5KiekisChanging(value);
					this.SendPropertyChanging();
					this._Det5Kiekis = value;
					this.SendPropertyChanged("Det5Kiekis");
					this.OnDet5KiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det6Kodas", DbType="NChar(20)")]
		public string Det6Kodas
		{
			get
			{
				return this._Det6Kodas;
			}
			set
			{
				if ((this._Det6Kodas != value))
				{
					this.OnDet6KodasChanging(value);
					this.SendPropertyChanging();
					this._Det6Kodas = value;
					this.SendPropertyChanged("Det6Kodas");
					this.OnDet6KodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det6Kiekis", DbType="Int")]
		public System.Nullable<int> Det6Kiekis
		{
			get
			{
				return this._Det6Kiekis;
			}
			set
			{
				if ((this._Det6Kiekis != value))
				{
					this.OnDet6KiekisChanging(value);
					this.SendPropertyChanging();
					this._Det6Kiekis = value;
					this.SendPropertyChanged("Det6Kiekis");
					this.OnDet6KiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det7Kodas", DbType="NChar(20)")]
		public string Det7Kodas
		{
			get
			{
				return this._Det7Kodas;
			}
			set
			{
				if ((this._Det7Kodas != value))
				{
					this.OnDet7KodasChanging(value);
					this.SendPropertyChanging();
					this._Det7Kodas = value;
					this.SendPropertyChanged("Det7Kodas");
					this.OnDet7KodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det7Kiekis", DbType="Int")]
		public System.Nullable<int> Det7Kiekis
		{
			get
			{
				return this._Det7Kiekis;
			}
			set
			{
				if ((this._Det7Kiekis != value))
				{
					this.OnDet7KiekisChanging(value);
					this.SendPropertyChanging();
					this._Det7Kiekis = value;
					this.SendPropertyChanged("Det7Kiekis");
					this.OnDet7KiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det8Kodas", DbType="NChar(20)")]
		public string Det8Kodas
		{
			get
			{
				return this._Det8Kodas;
			}
			set
			{
				if ((this._Det8Kodas != value))
				{
					this.OnDet8KodasChanging(value);
					this.SendPropertyChanging();
					this._Det8Kodas = value;
					this.SendPropertyChanged("Det8Kodas");
					this.OnDet8KodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det8Kiekis", DbType="Int")]
		public System.Nullable<int> Det8Kiekis
		{
			get
			{
				return this._Det8Kiekis;
			}
			set
			{
				if ((this._Det8Kiekis != value))
				{
					this.OnDet8KiekisChanging(value);
					this.SendPropertyChanging();
					this._Det8Kiekis = value;
					this.SendPropertyChanged("Det8Kiekis");
					this.OnDet8KiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det9Kodas", DbType="NChar(20)")]
		public string Det9Kodas
		{
			get
			{
				return this._Det9Kodas;
			}
			set
			{
				if ((this._Det9Kodas != value))
				{
					this.OnDet9KodasChanging(value);
					this.SendPropertyChanging();
					this._Det9Kodas = value;
					this.SendPropertyChanged("Det9Kodas");
					this.OnDet9KodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Det9Kiekis", DbType="Int")]
		public System.Nullable<int> Det9Kiekis
		{
			get
			{
				return this._Det9Kiekis;
			}
			set
			{
				if ((this._Det9Kiekis != value))
				{
					this.OnDet9KiekisChanging(value);
					this.SendPropertyChanging();
					this._Det9Kiekis = value;
					this.SendPropertyChanged("Det9Kiekis");
					this.OnDet9KiekisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ParduotosDetales")]
	public partial class ParduotosDetale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _PardavimoSaskaitosNr;
		
		private string _DetKodas;
		
		private string _Pavadinimas;
		
		private string _Kiekis;
		
		private string _Matas;
		
		private string _KiekisSuMatu;
		
		private string _Pardavejas;
		
		private string _PardavimoSuma;
		
		private string _rezerv;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPardavimoSaskaitosNrChanging(string value);
    partial void OnPardavimoSaskaitosNrChanged();
    partial void OnDetKodasChanging(string value);
    partial void OnDetKodasChanged();
    partial void OnPavadinimasChanging(string value);
    partial void OnPavadinimasChanged();
    partial void OnKiekisChanging(string value);
    partial void OnKiekisChanged();
    partial void OnMatasChanging(string value);
    partial void OnMatasChanged();
    partial void OnKiekisSuMatuChanging(string value);
    partial void OnKiekisSuMatuChanged();
    partial void OnPardavejasChanging(string value);
    partial void OnPardavejasChanged();
    partial void OnPardavimoSumaChanging(string value);
    partial void OnPardavimoSumaChanged();
    partial void OnrezervChanging(string value);
    partial void OnrezervChanged();
    #endregion
		
		public ParduotosDetale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PardavimoSaskaitosNr", DbType="NVarChar(15)")]
		public string PardavimoSaskaitosNr
		{
			get
			{
				return this._PardavimoSaskaitosNr;
			}
			set
			{
				if ((this._PardavimoSaskaitosNr != value))
				{
					this.OnPardavimoSaskaitosNrChanging(value);
					this.SendPropertyChanging();
					this._PardavimoSaskaitosNr = value;
					this.SendPropertyChanged("PardavimoSaskaitosNr");
					this.OnPardavimoSaskaitosNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetKodas", DbType="NVarChar(20)")]
		public string DetKodas
		{
			get
			{
				return this._DetKodas;
			}
			set
			{
				if ((this._DetKodas != value))
				{
					this.OnDetKodasChanging(value);
					this.SendPropertyChanging();
					this._DetKodas = value;
					this.SendPropertyChanged("DetKodas");
					this.OnDetKodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pavadinimas", DbType="NVarChar(100)")]
		public string Pavadinimas
		{
			get
			{
				return this._Pavadinimas;
			}
			set
			{
				if ((this._Pavadinimas != value))
				{
					this.OnPavadinimasChanging(value);
					this.SendPropertyChanging();
					this._Pavadinimas = value;
					this.SendPropertyChanged("Pavadinimas");
					this.OnPavadinimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kiekis", DbType="NVarChar(10)")]
		public string Kiekis
		{
			get
			{
				return this._Kiekis;
			}
			set
			{
				if ((this._Kiekis != value))
				{
					this.OnKiekisChanging(value);
					this.SendPropertyChanging();
					this._Kiekis = value;
					this.SendPropertyChanged("Kiekis");
					this.OnKiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matas", DbType="NVarChar(10)")]
		public string Matas
		{
			get
			{
				return this._Matas;
			}
			set
			{
				if ((this._Matas != value))
				{
					this.OnMatasChanging(value);
					this.SendPropertyChanging();
					this._Matas = value;
					this.SendPropertyChanged("Matas");
					this.OnMatasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KiekisSuMatu", DbType="NVarChar(15)")]
		public string KiekisSuMatu
		{
			get
			{
				return this._KiekisSuMatu;
			}
			set
			{
				if ((this._KiekisSuMatu != value))
				{
					this.OnKiekisSuMatuChanging(value);
					this.SendPropertyChanging();
					this._KiekisSuMatu = value;
					this.SendPropertyChanged("KiekisSuMatu");
					this.OnKiekisSuMatuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pardavejas", DbType="NVarChar(30)")]
		public string Pardavejas
		{
			get
			{
				return this._Pardavejas;
			}
			set
			{
				if ((this._Pardavejas != value))
				{
					this.OnPardavejasChanging(value);
					this.SendPropertyChanging();
					this._Pardavejas = value;
					this.SendPropertyChanged("Pardavejas");
					this.OnPardavejasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PardavimoSuma", DbType="NVarChar(10)")]
		public string PardavimoSuma
		{
			get
			{
				return this._PardavimoSuma;
			}
			set
			{
				if ((this._PardavimoSuma != value))
				{
					this.OnPardavimoSumaChanging(value);
					this.SendPropertyChanging();
					this._PardavimoSuma = value;
					this.SendPropertyChanged("PardavimoSuma");
					this.OnPardavimoSumaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezerv", DbType="NChar(10)")]
		public string rezerv
		{
			get
			{
				return this._rezerv;
			}
			set
			{
				if ((this._rezerv != value))
				{
					this.OnrezervChanging(value);
					this.SendPropertyChanging();
					this._rezerv = value;
					this.SendPropertyChanged("rezerv");
					this.OnrezervChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
